### ISSUE TITLE
Error when creating a new location without PERMANENT mapset

### ISSUE THREAD

**Issue by lrntct** [zarch/grass-session#17]
Thanks a lot for this very useful tool!

When creating a new location and mapset that is not PERMANENT, subsequent GRASS operations fail because they expect a PERMANENT mapset. For example:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import tempfile

import grass_session
import grass.script as gscript

session = grass_session.Session()
tmpdir = tempfile.mkdtemp()
session.open(gisdb=tmpdir,
             location='xy',
             mapset='test',
             create_opts='XY',
             loadlibs=True)

region = gscript.read_command('g.region', flags='p')
```

Fails with the following error:

```
Loading libraries from /usr/lib/grass78/lib
ERROR: Unable to open element file <> for <DEFAULT_WIND@PERMANENT>
Traceback (most recent call last):
  File "test_grass_session.py", line 17, in <module>
    region = gscript.read_command('g.region', flags='p')
  File "/usr/lib/grass78/etc/python/grass/script/core.py", line 503, in read_command
    return handle_errors(returncode, stdout, args, kwargs)
  File "/usr/lib/grass78/etc/python/grass/script/core.py", line 342, in handle_errors
    raise CalledModuleError(module=None, code=code,
grass.exceptions.CalledModuleError: Module run None g.region -p ended with error
Process ended with non-zero return code 1. See errors in the (error) output.
```

Maybe it could be possible to automatically create a PERMANENT mapset when one does not exists?

**Comment by zarch** [comment]
Hi @lrntct, 
sorry for the delay, yes it fails if the PERMANENT mapset is not created. To me this behaviour it seems coherent on how the grass command it is working at the moment, in fact from the command line, if you are creating a new location you can only specify the location, then as second step you can create a mapset.

```bash
$ grass78 -c epsg:3035 myloc --exec g.gisenv    
Starting GRASS GIS...
Creating new GRASS GIS location <myloc>...
Cleaning up temporary files...
Executing <g.gisenv> ...
GISDBASE=/tmp/grasstest
LOCATION_NAME=myloc
MAPSET=PERMANENT
GUI=wxpython
Execution of <g.gisenv> finished.
Cleaning up temporary files...


$ tree myloc                                            
myloc
└── PERMANENT
    ├── DEFAULT_WIND
    ├── MYNAME
    ├── PROJ_EPSG
    ├── PROJ_INFO
    ├── PROJ_UNITS
    ├── sqlite
    ├── VAR
    └── WIND

2 directories, 7 files


$ grass78 -c myloc/mymapset --exec g.gisenv
Starting GRASS GIS...
Creating new GRASS GIS mapset <mymapset>...
Cleaning up temporary files...
Executing <g.gisenv> ...
GISDBASE=/tmp/grasstest
LOCATION_NAME=myloc
MAPSET=mymapset
GUI=wxpython
Execution of <g.gisenv> finished.
Cleaning up temporary files...


$ tree myloc                               
myloc
├── mymapset
│   ├── sqlite
│   ├── VAR
│   └── WIND
└── PERMANENT
    ├── DEFAULT_WIND
    ├── MYNAME
    ├── PROJ_EPSG
    ├── PROJ_INFO
    ├── PROJ_UNITS
    ├── sqlite
    ├── VAR
    └── WIND

4 directories, 9 files
```
As you see, as far as I know there is no way to create directly the mapset without using this two steps. 
`grass-session` try to follow the same behaviour of grass, so you can use: `Session(gisdb="/tmp", location="location", create_opts="EPSG:3035")` to create the `PERMANENT` mapset and then execute: `Session(gisdb="/tmp", location="location", mapset="test", create_opts="")` to create your mapset.

This it make sense to me because when you are working generally you create your location with the PERMANENT, and then you create several dedicated mapsets for different tasks or pipeline processes. 
Personally I would not like to introduce "magic" expecially if not consistent with the GRASS GIS behaviour.
