### ISSUE TITLE
How to handle the --overwrite argument (or --verbose, ...) of a grass module?

### ISSUE THREAD

**Issue by nobohan** [zarch/grass-session#6]
Hello!

I'm using grass-session to use some GRASS modules in a loop. I'd like to overwrite the layers at each loop iteration, but I don't see how to use the `--overwrite` (or whatever "--argument") in the GRASS module.

```
    gcore.parse_command('r.in.gdal --overwrite',
                        input=data_dir + 'dem.tif',
                        output='dem',
                        flags='o'
                        )
```

or :
```
    gcore.parse_command('r.in.gdal',
                        input=data_dir + 'dem.tif',
                        output='dem',
                        flags='o',
                        '--overwrite'
                        )
```

To circumvent the issue, I'm removing the whole GRASS location folder at each loop iteration. But there might be a simpler way. 

Thanks,

**Comment by dollarklavs** [comment]
Hi,
I use `from grass.pygrass.modules import Module` and create grass functions like so:
`r_out_gdal = Module('r.out.gdal')`
and finally access them like this:
`r_out_gdal(overwrite=True,input=viewshedname,output=out_filepath)`
The important thing here, which I hope will also work for you is `overwrite=True`
// Jonas

**Comment by zarch** [comment]
Hi @nobohan,
sorry for the delay, as already answered by dollarklavs, all the special flags in grass are trasformed as a boolean variable in python, so from `--verbose` to `verbose=True`, from `--overwrite` to `overwrite=True`, from `--quite` to `quite=True`, etc.

And you can use consistently in `grass.script.core` functions (`run_module`, `parse_command`, etc) as well as in `grass.pygrass.modules` classes (`Module`, `ParallelModule`, `GridModule`).

I'm going to close this since, from my understanding, is not a `grass-session` issue.
Feel free to re-open the issue if is not the case.
